### ISSUE TITLE
visualize package

### ISSUE THREAD

**Issue by ramess101** [mosdef-hub/mosdef_tutorials#12]
@summeraz 

Andrew,

It was good meeting you at FOMMS a few weeks ago. I have finally gotten around to trying to implement mbuild and foyer. I successfully installed all the needed software to run the "Individual Tutorial Overview", except for visualize. I tried "pip install visualize" and searching for it online, but to no avail. Where can I find visualize? For now, I have just commented out everywhere that visualize is found in the jupyter notebook, but that is obviously not the ideal solution.

Thanks

Rich

**Comment by summeraz** [comment]
Good to hear from you Rich! So just to clarify, you are receiving an error when running commands similar to `Compound.visualize()`? This method uses the `nglview` package for visualization, so perhaps you do not have that package installed.

Also, if you wanted to work through the overview tutorial while we try to sort out this issue with the visualization, you can access it through this [Binder link](https://mybinder.org/v2/gh/mosdef-hub/mosdef_tutorials/master?filepath=overview.ipynb).

**Comment by ramess101** [comment]
@summeraz 

Actually the "from visualize import visualize" command was returning: ImportError: No module named visualize

But we think we just figured out the issue. visualize.py was removed in Commit #39 it appears. So we just need to roll back a few commits and download visualize.py.

We did try use the Binder link also but for some reason it would never load. Maybe it was just our internet? We were able to use the non-interactive version on Binder link though.

Anyways, I will be in touch if/when we meet further challenges :-) 

Thanks again

**Comment by summeraz** [comment]
It sounds like you may not have the latest version of the repo. For visualization within the notebooks we use a package called `nglview`. We were having issues with `nglview` at one point, and so as a stopgap solution were using that `visualize.py` script. However, `nglview` is now working and the latest version of the repo shouldn't have any `from visualize import visualize` statements. If it does, that's a mistake and those should be removed.

Binder can be hit-or-miss. I'm usually able to get the link to load eventually, but sometime it takes several minutes or needs to be refreshed.

**Comment by ramess101** [comment]
That may be true. This was actually in the mosdef_workshop repository (https://github.com/summeraz/mosdef_workshop) and "git pull origin master" says that I am already up-to-date. But since this repository is not under the mosdef-hub, perhaps it is no longer being used?  

At any rate, I think we just need to use the mosdef_tutorials repository instead (https://github.com/mosdef-hub/mosdef_tutorials) since that appears to be updated more frequently. We will let you know if we run into any additional issues (and hopefully some of them will be productive). 

Thanks!

**Comment by summeraz** [comment]
Ah okay, yes the `mosdef_workshop` repository was created for our workshop at AIChE last year. That repository not currently being updated. So you are correct that this repo (`mosdef_tutorials`) is the one to use, and the one we will be continuing to update as the software evolves.

I'm going to close this issue for now, but if you run into any other problems please open additional issues!
